server.port=10001

sop-service.base-url=https://confluence.dev.e2open.com
sop-service.username=tpalei
sop-service.password=Keepitsimple@23456
sop-service.confluence-space-key=~tpalei
sop-service.title=Trying+Spring+AI

remote.ssh.host=lsp-dev02-fr4.blujay.global
remote.ssh.port=22
remote.ssh.username=tapankumar.palei
remote.ssh.password=Keepitsimple@23456
remote.ssh.timeout-ms=100000
spring.ai.mcp.client.request-timeout=120s

spring.ai.vectorstore.qdrant.host=localhost
spring.ai.vectorstore.qdrant.port=6334
spring.ai.vectorstore.qdrant.collection-name=sop-v01
spring.ai.vectorstore.qdrant.initialize-schema=true

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.embedding.model=nomic-embed-text
spring.ai.ollama.embedding.enabled=true
spring.ai.ollama.chat.enabled=false

spring.ai.openai.base-url=https://llm-gateway.wtg.zone
spring.ai.openai.chat.options.model=gpt-5.4
#spring.ai.openai.api-key=sk-wFFWQVZP34YpzQzeshP-WQ
spring.ai.openai.api-key=${WST_OPENAI_API_KEY}
spring.ai.openai.chat.api-key=${spring.ai.openai.api-key}
spring.ai.openai.embedding.enabled=false

spring.ai.mcp.client.sse.connections.mcpserver.url=http://localhost:9090
spring.ai.tools.enabled=true
spring.ai.openai.chat.options.tool-choice=auto
