spring.application.name=load-sop-qdrant

server.port=10001

sop-service.base-url=https://confluence.dev.e2open.com
sop-service.username=tpalei
sop-service.password=Keepitsimple@123456
sop-service.api-endpoint=/rest/api/content?spaceKey=~tpalei&title=Fixing+Instance+Not+Running&expand=body.storage


remote.ssh.host=lsp-dev02-fr4.blujay.global
remote.ssh.port=22
remote.ssh.username=tapankumar.palei
remote.ssh.password=Keepitsimple@23456
remote.ssh.timeout-ms=10000